### ISSUE TITLE
About testing on real data

### ISSUE THREAD

**Issue by YinghaoHuang91** [wilfer9008/CNN_IMU#2]
Hi Fernando,

I like your work pretty much, and thank you for making the code public. I'd like to know, if I want to test the trained model on real data, how should I place the IMUs more specifically? Like the orientation, angle, position, etc. Or the method is pretty robust to the configuration? 

Thanks!

Yinghao

**Comment by wilfer9008** [comment]
HI Yinghao,

We have tested the network on real data (data recorded from IMUs on a real application). 
Specifically, there is no only-one-rule for placing the IMUs. ONe should follow the dataset procedure itself. You have to take into account that the training and testing setups should be the same, similar IMUS in similar human body places. 
We are currently carrying out experiments for different IMU-positions and configurations, and the results are robust in the sense of constant. There is no variation on performance for slightly different positions and orientations of IMUs.

Any further question, do not hesitate in contacting me.

Best regards,
Fernando
